### ISSUE TITLE
No such file or directory: "install"

### ISSUE THREAD

**Issue by mathieusibilla** [jellyfin/jellyfin-ios#92]
Hi,
I try to install following the build process, step 1 works not issues, on step 2 I get an error:`{Errno2} No such file or directory: 'install' `

This is the content of the directory:
```bash
mathieu@bubuntu:/home$ cd jellyfin-expo/
mathieu@bubuntu:/home/jellyfin-expo$ ls -al
total 712
drwxr-xr-x 11 root root   4096 Jun 22 21:38 .
drwxr-xr-x  4 root root   4096 Jun 22 21:31 ..
-rw-r--r--  1 root root   1982 Jun 22 21:31 App.js
-rw-r--r--  1 root root    826 Jun 22 21:31 app.json
drwxr-xr-x  4 root root   4096 Jun 22 21:31 assets
-rw-r--r--  1 root root    316 Jun 22 21:31 babel.config.js
drwxr-xr-x  2 root root   4096 Jun 22 21:31 components
drwxr-xr-x  2 root root   4096 Jun 22 21:31 constants
-rw-r--r--  1 root root   1440 Jun 22 21:31 .eslintrc.json
drwxr-xr-x  8 root root   4096 Jun 22 21:31 .git
-rw-r--r--  1 root root    111 Jun 22 21:31 .gitignore
drwxr-xr-x 10 root root   4096 Jun 22 21:38 jellyfin-expo
-rw-r--r--  1 root root  16725 Jun 22 21:31 LICENSE
drwxr-xr-x  2 root root   4096 Jun 22 21:31 navigation
-rw-r--r--  1 root root   1530 Jun 22 21:31 package.json
-rw-r--r--  1 root root    683 Jun 22 21:31 README.md
drwxr-xr-x  2 root root   4096 Jun 22 21:31 screens
drwxr-xr-x  2 root root   4096 Jun 22 21:31 __tests__
drwxr-xr-x  2 root root   4096 Jun 22 21:31 utils
-rw-r--r--  1 root root      3 Jun 22 21:31 .watchmanconfig
-rw-r--r--  1 root root 628643 Jun 22 21:31 yarn.lock
mathieu@bubuntu:/home/jellyfin-expo$ 
```

what am I doing wrong? please help

**Comment by thornbill** [comment]
What version of yarn are you using? You can run `yarn -v` to check. You can also use npm if yarn is causing problems. Just run `npm install` instead of `yarn install`.

**Comment by mathieusibilla** [comment]
Hi, 

Thanks for the feedback,

Npm isn't working either, this ubuntu VM is running on XCP-ng, could it be the cause? 
Here's the output of npm install:
```bash
mathieu@bubuntu:/home/jellyfin-expo$ yarn --version
0.32
mathieu@bubuntu:/home/jellyfin-expo$ sudo npm install
npm ERR! Linux 4.15.0-106-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jellyfin-expo/npm-debug.log
mathieu@bubuntu:/home/jellyfin-expo$ 
```

I'm really looking to switch to JF and would really like to crack this issue, any help would be greatly appreciated :-)

**Comment by anthonylavado** [comment]
@mathieusibilla As a side question, where do you want to use this app? We currently have it on the iOS App Store. It can be made to work with Android as an alternative to the other Android clients.

**Comment by mathieusibilla** [comment]
@anthonylavado Mainly on my own network at home. I have the iOS app installed on my phone but it refuse any server address I enter. So do I need this jellyfin-expo to allow streaming on other (wireless) devices?

**Comment by mathieusibilla** [comment]
@anthonylavado Hey it's working using the app. I completelly miss understood the instructions i think. Thanks to all for your help
